version: "3.7"
services:
  app:
    build:
      args:
        user: inoreds
        uid: 7717717
      context: ./
      dockerfile: Dockerfile
    image: boxbilling
    container_name: boxbilling-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - boxbilling

  db:
    image: mysql:5.7
    container_name: boxbilling-db
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    environment:
      MYSQL_DATABASE: boxbilling_db
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - boxbilling

  nginx:
    image: nginx:alpine
    container_name: boxbilling-nginx
    restart: unless-stopped
    ports:
      - 8004:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - boxbilling

networks:
  boxbilling:
    driver: bridge